package selenideide;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.WebDriverRunner;
import static com.codeborne.selenide.Selectors.*;
import static com.codeborne.selenide.Condition.*;
import static com.codeborne.selenide.Selenide.*;
import static org.junit.jupiter.api.Assertions.*;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;
import java.util.*;
public class StudentsRegistrationFormSelenideTest {
  private Map<String, Object> vars;
  @BeforeEach
  public void setUp() {
    Configuration.browser = "chrome";
    vars = new HashMap<>();
  }
  @AfterEach
  public void tearDown() {
  }
  @Test
  public void studentsRegistrationFormTest() {
    open("https://demoqa.com/automation-practice-form");
    WebDriverRunner.getWebDriver().manage().window().setSize(new Dimension(1936, 1056));
    $("#firstName").click();
    $("#firstName").val("egor");
    $("#lastName").val("ivanov");
    $("#userEmail").val("egor@ivanov.com");
    $(".custom-radio:nth-child(1) > .custom-control-label").click();
    $("#userNumber").click();
    $("#userNumber").val("1231231234");
    $("#dateOfBirthInput").click();
    $(".react-datepicker__month-select").click();
    $(".react-datepicker__month-select").selectOption("May");
    $(".react-datepicker__month-select").click();
    $(".react-datepicker__year-select").click();
    $(".react-datepicker__year-select").selectOption("1961");
    $(".react-datepicker__year-select").click();
    $(".react-datepicker__day--025").click();
    $(".subjects-auto-complete__value-container").click();
    $("#react-select-2-option-1").click();
    $(".custom-checkbox:nth-child(2) > .custom-control-label").click();
    $(".custom-checkbox:nth-child(3) > .custom-control-label").click();
    $("#uploadPicture").click();
    $("#uploadPicture").val("C:\\fakepath\\Screenshot_1.png");
    $("#currentAddress").click();
    $("#currentAddress").val("moskow");
    actions().moveToElement($(".css-1pahdxg-control > .css-1hwfws3")).clickAndHold().perform();
    actions().moveToElement($(".css-5k7hxh")).release().perform();
    $("#state").click();
    $("#currentAddress").click();
    $("#currentAddress").click();
    $("#currentAddress").val("kiev");
    $("#currentAddress-wrapper > .col-md-3").click();
    $("#currentAddress").click();
    $("#currentAddress").val("Kiev");
    $(".css-1gtu0rj-indicatorContainer").click();
    $("#react-select-3-option-1").click();
    $(".css-1pahdxg-control > .css-1hwfws3").click();
    $("#react-select-4-option-1").click();
    $("#submit").click();
    $("tr:nth-child(1) > td:nth-child(2)").click();
    $("tr:nth-child(1) > td:nth-child(2)").shouldHave(text("egor ivanov"));
    $("tr:nth-child(3) > td:nth-child(2)").click();
    $("#closeLargeModal").click();
    $(".col-12:nth-child(3)").click();
  }
}
