package selenideide;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class StudentsRegistrationFormTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void studentsRegistrationFormTest() {
    driver.get("https://demoqa.com/automation-practice-form");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("egor");
    driver.findElement(By.id("lastName")).sendKeys("ivanov");
    driver.findElement(By.id("userEmail")).sendKeys("egor@ivanov.com");
    driver.findElement(By.cssSelector(".custom-radio:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("userNumber")).click();
    driver.findElement(By.id("userNumber")).sendKeys("1231231234");
    driver.findElement(By.id("dateOfBirthInput")).click();
    driver.findElement(By.cssSelector(".react-datepicker__month-select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".react-datepicker__month-select"));
      dropdown.findElement(By.xpath("//option[. = 'May']")).click();
    }
    driver.findElement(By.cssSelector(".react-datepicker__month-select")).click();
    driver.findElement(By.cssSelector(".react-datepicker__year-select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".react-datepicker__year-select"));
      dropdown.findElement(By.xpath("//option[. = '1961']")).click();
    }
    driver.findElement(By.cssSelector(".react-datepicker__year-select")).click();
    driver.findElement(By.cssSelector(".react-datepicker__day--025")).click();
    driver.findElement(By.cssSelector(".subjects-auto-complete__value-container")).click();
    driver.findElement(By.id("react-select-2-option-1")).click();
    driver.findElement(By.cssSelector(".custom-checkbox:nth-child(2) > .custom-control-label")).click();
    driver.findElement(By.cssSelector(".custom-checkbox:nth-child(3) > .custom-control-label")).click();
    driver.findElement(By.id("uploadPicture")).click();
    driver.findElement(By.id("uploadPicture")).sendKeys("C:\\fakepath\\Screenshot_1.png");
    driver.findElement(By.id("currentAddress")).click();
    driver.findElement(By.id("currentAddress")).sendKeys("moscow");
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1pahdxg-control > .css-1hwfws3"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".css-5k7hxh"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("state")).click();
    driver.findElement(By.id("currentAddress")).click();
    driver.findElement(By.id("currentAddress")).click();
    driver.findElement(By.id("currentAddress")).sendKeys("kiev");
    driver.findElement(By.cssSelector("#currentAddress-wrapper > .col-md-3")).click();
    driver.findElement(By.id("currentAddress")).click();
    driver.findElement(By.id("currentAddress")).sendKeys("Kiev");
    driver.findElement(By.cssSelector(".css-1gtu0rj-indicatorContainer")).click();
    driver.findElement(By.id("react-select-3-option-1")).click();
    driver.findElement(By.cssSelector(".css-1pahdxg-control > .css-1hwfws3")).click();
    driver.findElement(By.id("react-select-4-option-1")).click();
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).getText(), is("egor ivanov"));
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).click();
    driver.findElement(By.id("closeLargeModal")).click();
    driver.findElement(By.cssSelector(".col-12:nth-child(3)")).click();
  }
}
